language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - cd frontend
  - npm install
  - npm start & wait-on http://localhost:3000
  - npx cypress open
on:
  branch: travis