language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - cd frontend
  - npm install
  - npm start & 
  - npx cypress open --record --key=abc123
on:
  branch: travis